### ISSUE TITLE
[BUG] Certain event functions are not executed when used together (onScenario, onStep)

### ISSUE THREAD

**Issue by gula123** [gherking/gherking#54]
## Summary
Certain event functions are not executed when used together (onScenario, onStep)

## Steps to Reproduce
1. Have the attached feature file
2. Have a simple precompiler that uses one of the inherited precompiler functions:
Example: `onStep(step: Step) {
        step.text = "test";
    }`
3. Execute the precompiler on the attached feature file
4. Observe the precompiled feature file content

### Expected behavior
4. The change defined in the onStep function should be applied to all the steps in the feature file in any depth

### Actual behavior
4. Steps are not changed according to the modification defined in the onStep function

### Note
Other precompiler functions are also affected
The issue is reproducible with child Elements (e.g. Steps of a scenario, Scenario of a rule, etc)

## Feature file
```

@tag1 @tag2
Feature: Hello world
  As a smth
  I want to do smth
  So that I am smth

  Rule: Name of the rule
    Description of the rule

    Background:
    Description

      Given this is a given step
      And this is a given step too
      When this is a when step
      And this is a when step too
      Then it should be a then step
      And it should be a then step too

    @tag2 @tag3
    Scenario: Name of scenario
    Description of the scenario

      Given this is a given step
      And this is a given step too
      When this is a when step with data table
        | val1 |
        | val2 |
        | val3 |
      And this is a when step with data table too
        | col1 | col2 |
        | val1 | val2 |
        | val3 | val4 |
      And this is a when step with doc string
        """
        Hello world
        Hello World
        hello World
        hello world
        """
      Then it should be a then step
      And it should be a then step too

    Scenario: Name of scenario
    Description of the scenario

      Given this is a given step
      And this is a given step too
      When this is a when step with data table
      Then it should be a then step

    @tag2 @tag(3)
    Scenario Outline: Name of scenario outline
      Given this is a given step
      And this is a given step too
      When this is a when step <key>
      And this is a when step too <key2>
      Then it should be a then step
      And it should be a then step too

    @tagE1
      Examples: First examples
        | key    | key2   |
        | value1 | value2 |
        | value3 | value4 |

      Examples: Second examples
        | key    |
        | value2 |


```

**Comment by szikszail** [comment]
The issue is fixed in `v1.0.0-beta.5`

**Comment by gula123** [comment]
The issue is still reproducible with the following feature file by not changing table header or table row values

`@tag1 @${keyword1}
Feature: Hello world ${keyword1}
  As a smth
  I want to do ${keyword2}
  So that I am smth

  Rule: Rule name with replaced ${keyword2}
    Rule Description and replaced ${keyword1}

    Background: Name ${keyword2}
      Description ${keyword1}

      Given test is a given ${keyword1}
      And this is a given step too
      When this is a when step
      And this is a when step too
      Then it should be a then step
      And it should be a then step too

    @tag2 @${keyword1}
    Scenario: ${keyword1} Name of scenario
      ${keyword2} Description of the scenario

      Given this is a given ${keyword1}
      And this is a given step too
      When this is a when step with data table
        | val1 |
        | val2 |
        | val3 |
      And this is a when step with data table too
        | col1 | col2 |
        | val1 | val2 |
        | val3 | val4 |
      And this is a when step with doc string
        """
        Hello world
        Hello World
        hello World
        hello world
        """
      Then it should be a then step
      And it should be a then step too

    Scenario: Name of scenario
      Description of the scenario

      Given this is a given step
      And this is a given step too
      When this is a when step with data table
      Then it should be a then step

    @${keyword2} @tag(3)
    Scenario Outline: Name of scenario outline ${keyword1}
      Scenario outline ${keyword2} description
      Given this is a ${keyword2} step
      And this is a given step too
      When this is a when step <key>
      And this is a when step too <key2>
      Then it should be a then step
      And it should be a then step too

      @${keyword1}
      Examples: Replace in table header
        | ${keyword1} | key2   |
        | value1      | value2 |
        | value3      | value4 |

      Examples: Replace in table row
        | key         |
        | ${keyword2} |

**Comment by szikszail** [comment]
@gula123  please share the precompiler config (including events) you use.

**Comment by gula123** [comment]
import { PreCompiler } from "gherking";
    import { Background, DataTable, DocString, Examples, Feature, Rule, Scenario, ScenarioOutline, Step, TableRow, Tag } from 
    "gherkin-ast";
    //eslint-disable-next-line @typescript-eslint/no-var-requires
    //const debug = require("debug")("gpc:template");

    type Config = {
        [key: string]: string;
    };

    class Replacer implements PreCompiler {
        config: Config;
        constructor(config: Config) {
            if (typeof config !== 'object') {
                throw new TypeError('Configuration is not an object: ' + config);
            }
            this.config = config;
        }

        _replaceAll<T, K extends keyof T>(obj: T, ...keys: K[]) {
            keys.forEach(key => {
                if (obj[key]) {
                    Object.keys(this.config).forEach(toReplace => {
                        const replaceWith = this.config[toReplace];
                            //@ts-ignore
                            obj[key] = obj[key].replace(new RegExp('\\$\\{' + toReplace + '\\}', 'gi'), replaceWith);
                    });
                }
            });
        }

        _replaceInTableRow(row: TableRow) {
            row.cells.forEach(cell => {
                this._replaceAll(cell, 'value');
            });
        }

        onFeature(feature: Feature) {
            this._replaceAll(feature, 'name', 'description');
        }

        onRule(rule: Rule) {
            this._replaceAll(rule, 'name', 'description');
        }

        onBackground(background: Background) {
            this._replaceAll(background, 'name', 'description');
        }

        onScenarioOutline(scenarioOutline: ScenarioOutline) {
            this._replaceAll(scenarioOutline, 'name', 'description');
        }

        onScenario(scenario: Scenario) {
            this._replaceAll(scenario, 'name', 'description');
        }

        onStep(step: Step) {
            this._replaceAll(step, 'text');
        }

        onTag(tag: Tag) {
            this._replaceAll(tag, 'name');
        }

        onExamples(examples: Examples) {
            this._replaceAll(examples, 'name');
        }

        onDocString(docString: DocString) {
            this._replaceAll(docString, 'content');
        }

        onDataTable(dataTable: DataTable) {
            dataTable.rows.forEach(row => {
                this._replaceInTableRow(row);
            })
        }

        onExampleRow(exampleRow: TableRow) {
            this._replaceInTableRow(exampleRow);
        }

        onExampleHeader(exampleHeader: TableRow) {
            this._replaceInTableRow(exampleHeader);
        }
    }
    export = Replacer

**Comment by szikszail** [comment]
@gula123 
First of all, in the new API of the gherking, there are no such events functions as `onExampleRow` and `onExampleHeader`, please use `onTableRow`, which is now applied to the header of the example as well.
Please use `gherking@1.0.0-beta.6`

**Comment by gula123** [comment]
Using the test feature file above and the following events:

    import { PreCompiler } from "gherking";
    import { Background, DataTable, DocString, Examples, Feature, Rule, Scenario, ScenarioOutline, Step, TableRow, Tag } from     "gherkin-ast";
    //eslint-disable-next-line @typescript-eslint/no-var-requires
    //const debug = require("debug")("gpc:template");
    
    type Config = {
        [key: string]: string;
    };
    
    class Replacer implements PreCompiler {
    config: Config;
    constructor(config: Config) {
        if (typeof config !== 'object') {
            throw new TypeError('Configuration is not an object: ' + config);
        }
        this.config = config;
    }

    _replaceAll<T, K extends keyof T>(obj: T, ...keys: K[]): void {
        keys.forEach(key => {
            if (obj[key]) {
                Object.keys(this.config).forEach(toReplace => {
                    const replaceWith = this.config[toReplace];
                        //@ts-ignore
                        obj[key] = obj[key].replace(new RegExp('\\$\\{' + toReplace + '\\}', 'gi'), replaceWith);
                });
            }
        });
    }

    _replaceInTableRow(row: TableRow): void {
        row.cells.forEach(cell => {
            this._replaceAll(cell, 'value');
        });
    }

    onFeature(feature: Feature): void {
        this._replaceAll(feature, 'name', 'description');
    }

    onRule(rule: Rule): void {
        this._replaceAll(rule, 'name', 'description');
    }

    onBackground(background: Background): void {
        this._replaceAll(background, 'name', 'description');
    }

    onScenarioOutline(scenarioOutline: ScenarioOutline): void {
        this._replaceAll(scenarioOutline, 'name', 'description');
    }

    onScenario(scenario: Scenario): void {
        this._replaceAll(scenario, 'name', 'description');
    }

    onStep(step: Step): void {
        this._replaceAll(step, 'text');
    }

    onTag(tag: Tag): void {
        this._replaceAll(tag, 'name');
    }

    onExamples(examples: Examples): void {
        this._replaceAll(examples, 'name');
    }

    onDocString(docString: DocString): void {
        this._replaceAll(docString, 'content');
    }

    onDataTable(dataTable: DataTable): void {
        dataTable.rows.forEach(row => {
            this._replaceInTableRow(row);
        })
    }

    onTableRow(exampleRow: TableRow): void {
        this._replaceInTableRow(exampleRow);
    }
    }
    export = Replacer

The result will not contain the rule and its children:

    Document {
      _id: '084df4b3-55fe-46c5-9baa-398c79f33f12',
      feature: Feature {
        _id: '4d8b2ad7-54ea-4337-963f-4133966bd23c',
        keyword: 'Feature',
        name: 'Hello world value1',
        description: 'As a smth\nI want to do value2\nSo that I am smth',
        language: 'en',
        elements: [],
        tags: [ [Tag], [Tag] ]
      }
    }

**Comment by szikszail** [comment]
@gula123 is the `elements` empty only after the processing or even it is not loaded before it?

**Comment by szikszail** [comment]
I checked it with `gherkin-io` (https://github.com/gherking/gherkin-io/commit/0723fcb68e959e49ee60ff8860d48fa8cd17f0e2) and rules are parsed correctly, thus the issue must be either in the `gherkin-ast`, `gherking` or in your precompiled

**Comment by szikszail** [comment]
@gula123  please check your branch in `gpc-replacer` repository, the root cause of the issue was most likely two-fold: not updated dependencies and incorrect API used to implement the replacer.
